version: '3'

services:
  mongo:
    image: mongo
    container_name: task-mongo
    ports:
      - "27017:27017"
    networks:
      - task-network
  task-app-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: task-app-api
    container_name: task-app-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    links:
      - mongo
    environment:
      - PORT=5000
      - MONGO_DB_CONNECTION_URI=mongodb://task-mongo:27017
      - MONGO_DB_DEFAULT=task_db
      - SERVICE_URL_CONTACT_TYPE_CLASSIFICATION=http://task-service-classification:5001/predict
      - SERVICE_URL_TAGGER=http://task-service-tagger:5002/predict
    networks:
      - task-network
networks:
  task-network:
    driver: bridge
    external: true